spring:
  application:
    name: moc
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: c##cucook_moc
    password: moc

  mail:
    host: smtp.gmail.com
    port: 587
    username: yun.junseo6365@gmail.com
    password: qzuigkadfwilpoeo # Gmail 앱 비밀번호 여기 넣기(16자리 띄어쓰기 없이 보안이슈로 유출되면 안됌 "" 없이 그대로 집어넣기 )
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8090

mybatis:
  mapper-locations: classpath:mybatis/mappers/*.xml
  type-aliases-package: com.cucook.moc.*.vo
  configuration:
    map-underscore-to-camel-case: true

#gemini:
#  api:
#    key: ""

app:
  frontend-base-url: http://localhost:3010
