spring.application.name=moc

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@YOUR_HOST:1521/YOUR_SERVICE_NAME
spring.datasource.username=c##cucook_moc
spring.datasource.password=moc

mybatis.mapper-locations=classpath:mybatis.mappers/*.xml
mybatis.type-aliases-package=com.cucook.moc.user.vo

server.port=8090